trigger:
- '*'

pool:
  vmImage: ubuntu-latest

variables:
  # timestamp: $[format('{0:yyyyMMdd}-{0:HHmmss}', pipeline.startTime)]
  parametersFilePath: $(Build.SourcesDirectory)/test/all-parameters.txt


jobs:
  - job: ReadParameters
    displayName: 'Read Parameters'
    steps:
    - task: PowerShell@2
      displayName: 'Read Parameters'
      inputs:
        targetType: 'inline'
        script: |
          $parametersFilePath = "$(Build.SourcesDirectory)/test/all-parameters.txt"
          Write-Host "parametersFilePath: $parametersFilePath"

          $parameters = Get-Content $parametersFilePath | ConvertFrom-StringData

          Write-Host "linkedservices_to_deploy = $($parameters.linkedservices_to_deploy)"
          Write-Host "datasets_to_deploy = $($parameters.datasets_to_deploy)"
          Write-Host "templates_to_deploy = $($parameters.templates_to_deploy)"

          Write-Output "##vso[task.setvariable variable=linkedservices_to_deploy]$($parameters.linkedservices_to_deploy)"
          Write-Output "##vso[task.setvariable variable=datasets_to_deploy]$($parameters.datasets_to_deploy)"
          Write-Output "##vso[task.setvariable variable=templates_to_deploy]$($parameters.templates_to_deploy)"

    - task: PowerShell@2
      displayName: 'Use Parameters'
      inputs:
        targetType: 'inline'
        script: |
          $linkedservices_to_deploy = "$(linkedservices_to_deploy)"
          $datasets_to_deploy = "$(datasets_to_deploy)"
          $templates_to_deploy = "$(templates_to_deploy)"
          Write-Host "Using parameters:"
          Write-Host "linkedservices_to_deploy = $linkedservices_to_deploy"
          Write-Host "datasets_to_deploy = $datasets_to_deploy"
          Write-Host "templates_to_deploy = $templates_to_deploy"