trigger: none

variables:
  user_azir_name: 'Release'

resources:
  repositories:
  - repository: source-repository
    type: git
    name: cdpadm-projects/adf-cdpadm
    ref: templates
  - repository: edwteam-repository
    type: git
    endpoint: sc-testing
    name: edw-projects/adf-edw
    ref: templates

# Call the template
extends:
  template: templates-deploy.yml
  parameters:
    teamRepository: edwteam-repository
    Linkedservices_to_deploy: LS111111*.json
    datasets_to_deploy: DS*.json
    templates_to_deploy: TS*.json
    user_azir_name: ${{ variables.user_azir_name }}